/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2' in SOPC Builder design 'kernel'
 * SOPC Builder design path: ../../kernel.sopcinfo
 *
 * Generated: Fri Dec 27 17:41:41 CST 2019
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00081820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x14
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x00040020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INST_ADDR_WIDTH 0x14
#define ALT_CPU_NAME "nios2"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00081000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00081820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x14
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x00040020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INST_ADDR_WIDTH 0x14
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00081000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_EPCS_FLASH_CONTROLLER
#define __ALTERA_AVALON_FIFO
#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_PIO
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_NIOS2_GEN2


/*
 * SCL configuration
 *
 */

#define ALT_MODULE_CLASS_SCL altera_avalon_pio
#define SCL_BASE 0x82180
#define SCL_BIT_CLEARING_EDGE_REGISTER 0
#define SCL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SCL_CAPTURE 0
#define SCL_DATA_WIDTH 1
#define SCL_DO_TEST_BENCH_WIRING 0
#define SCL_DRIVEN_SIM_VALUE 0
#define SCL_EDGE_TYPE "NONE"
#define SCL_FREQ 100000000
#define SCL_HAS_IN 0
#define SCL_HAS_OUT 1
#define SCL_HAS_TRI 0
#define SCL_IRQ -1
#define SCL_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SCL_IRQ_TYPE "NONE"
#define SCL_NAME "/dev/SCL"
#define SCL_RESET_VALUE 0
#define SCL_SPAN 16
#define SCL_TYPE "altera_avalon_pio"


/*
 * SDA configuration
 *
 */

#define ALT_MODULE_CLASS_SDA altera_avalon_pio
#define SDA_BASE 0x82170
#define SDA_BIT_CLEARING_EDGE_REGISTER 0
#define SDA_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SDA_CAPTURE 0
#define SDA_DATA_WIDTH 1
#define SDA_DO_TEST_BENCH_WIRING 0
#define SDA_DRIVEN_SIM_VALUE 0
#define SDA_EDGE_TYPE "NONE"
#define SDA_FREQ 100000000
#define SDA_HAS_IN 0
#define SDA_HAS_OUT 0
#define SDA_HAS_TRI 1
#define SDA_IRQ -1
#define SDA_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDA_IRQ_TYPE "NONE"
#define SDA_NAME "/dev/SDA"
#define SDA_RESET_VALUE 0
#define SDA_SPAN 16
#define SDA_TYPE "altera_avalon_pio"


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone IV GX"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x821f8
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x821f8
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x821f8
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "kernel"


/*
 * alarm_select configuration
 *
 */

#define ALARM_SELECT_BASE 0x82140
#define ALARM_SELECT_BIT_CLEARING_EDGE_REGISTER 1
#define ALARM_SELECT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ALARM_SELECT_CAPTURE 1
#define ALARM_SELECT_DATA_WIDTH 4
#define ALARM_SELECT_DO_TEST_BENCH_WIRING 0
#define ALARM_SELECT_DRIVEN_SIM_VALUE 0
#define ALARM_SELECT_EDGE_TYPE "RISING"
#define ALARM_SELECT_FREQ 100000000
#define ALARM_SELECT_HAS_IN 1
#define ALARM_SELECT_HAS_OUT 0
#define ALARM_SELECT_HAS_TRI 0
#define ALARM_SELECT_IRQ 3
#define ALARM_SELECT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define ALARM_SELECT_IRQ_TYPE "EDGE"
#define ALARM_SELECT_NAME "/dev/alarm_select"
#define ALARM_SELECT_RESET_VALUE 0
#define ALARM_SELECT_SPAN 16
#define ALARM_SELECT_TYPE "altera_avalon_pio"
#define ALT_MODULE_CLASS_alarm_select altera_avalon_pio


/*
 * epcs_flash configuration
 *
 */

#define ALT_MODULE_CLASS_epcs_flash altera_avalon_epcs_flash_controller
#define EPCS_FLASH_BASE 0x81000
#define EPCS_FLASH_IRQ 1
#define EPCS_FLASH_IRQ_INTERRUPT_CONTROLLER_ID 0
#define EPCS_FLASH_NAME "/dev/epcs_flash"
#define EPCS_FLASH_REGISTER_OFFSET 1024
#define EPCS_FLASH_SPAN 2048
#define EPCS_FLASH_TYPE "altera_avalon_epcs_flash_controller"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK LED_TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x821f8
#define JTAG_UART_IRQ 0
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * laser_fifo_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_laser_fifo_in_csr altera_avalon_fifo
#define LASER_FIFO_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define LASER_FIFO_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define LASER_FIFO_IN_CSR_BASE 0x82120
#define LASER_FIFO_IN_CSR_BITS_PER_SYMBOL 16
#define LASER_FIFO_IN_CSR_CHANNEL_WIDTH 0
#define LASER_FIFO_IN_CSR_ERROR_WIDTH 0
#define LASER_FIFO_IN_CSR_FIFO_DEPTH 2048
#define LASER_FIFO_IN_CSR_IRQ -1
#define LASER_FIFO_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LASER_FIFO_IN_CSR_NAME "/dev/laser_fifo_in_csr"
#define LASER_FIFO_IN_CSR_SINGLE_CLOCK_MODE 1
#define LASER_FIFO_IN_CSR_SPAN 32
#define LASER_FIFO_IN_CSR_SYMBOLS_PER_BEAT 2
#define LASER_FIFO_IN_CSR_TYPE "altera_avalon_fifo"
#define LASER_FIFO_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define LASER_FIFO_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define LASER_FIFO_IN_CSR_USE_AVALONST_SINK 1
#define LASER_FIFO_IN_CSR_USE_AVALONST_SOURCE 0
#define LASER_FIFO_IN_CSR_USE_BACKPRESSURE 1
#define LASER_FIFO_IN_CSR_USE_IRQ 0
#define LASER_FIFO_IN_CSR_USE_PACKET 0
#define LASER_FIFO_IN_CSR_USE_READ_CONTROL 0
#define LASER_FIFO_IN_CSR_USE_REGISTER 0
#define LASER_FIFO_IN_CSR_USE_WRITE_CONTROL 1


/*
 * laser_fifo_out configuration
 *
 */

#define ALT_MODULE_CLASS_laser_fifo_out altera_avalon_fifo
#define LASER_FIFO_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define LASER_FIFO_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define LASER_FIFO_OUT_BASE 0x821d0
#define LASER_FIFO_OUT_BITS_PER_SYMBOL 16
#define LASER_FIFO_OUT_CHANNEL_WIDTH 0
#define LASER_FIFO_OUT_ERROR_WIDTH 0
#define LASER_FIFO_OUT_FIFO_DEPTH 2048
#define LASER_FIFO_OUT_IRQ -1
#define LASER_FIFO_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LASER_FIFO_OUT_NAME "/dev/laser_fifo_out"
#define LASER_FIFO_OUT_SINGLE_CLOCK_MODE 1
#define LASER_FIFO_OUT_SPAN 8
#define LASER_FIFO_OUT_SYMBOLS_PER_BEAT 2
#define LASER_FIFO_OUT_TYPE "altera_avalon_fifo"
#define LASER_FIFO_OUT_USE_AVALONMM_READ_SLAVE 1
#define LASER_FIFO_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define LASER_FIFO_OUT_USE_AVALONST_SINK 1
#define LASER_FIFO_OUT_USE_AVALONST_SOURCE 0
#define LASER_FIFO_OUT_USE_BACKPRESSURE 1
#define LASER_FIFO_OUT_USE_IRQ 0
#define LASER_FIFO_OUT_USE_PACKET 0
#define LASER_FIFO_OUT_USE_READ_CONTROL 0
#define LASER_FIFO_OUT_USE_REGISTER 0
#define LASER_FIFO_OUT_USE_WRITE_CONTROL 1


/*
 * led_timer configuration
 *
 */

#define ALT_MODULE_CLASS_led_timer altera_avalon_timer
#define LED_TIMER_ALWAYS_RUN 0
#define LED_TIMER_BASE 0x820a0
#define LED_TIMER_COUNTER_SIZE 32
#define LED_TIMER_FIXED_PERIOD 0
#define LED_TIMER_FREQ 100000000
#define LED_TIMER_IRQ 2
#define LED_TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define LED_TIMER_LOAD_VALUE 99999
#define LED_TIMER_MULT 0.001
#define LED_TIMER_NAME "/dev/led_timer"
#define LED_TIMER_PERIOD 1
#define LED_TIMER_PERIOD_UNITS "ms"
#define LED_TIMER_RESET_OUTPUT 0
#define LED_TIMER_SNAPSHOT 1
#define LED_TIMER_SPAN 32
#define LED_TIMER_TICKS_PER_SEC 1000
#define LED_TIMER_TIMEOUT_PULSE_OUTPUT 0
#define LED_TIMER_TYPE "altera_avalon_timer"


/*
 * onchip_memory configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory altera_avalon_onchip_memory2
#define ONCHIP_MEMORY_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY_BASE 0x40000
#define ONCHIP_MEMORY_CONTENTS_INFO ""
#define ONCHIP_MEMORY_DUAL_PORT 0
#define ONCHIP_MEMORY_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_INIT_CONTENTS_FILE "kernel_onchip_memory"
#define ONCHIP_MEMORY_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY_IRQ -1
#define ONCHIP_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY_NAME "/dev/onchip_memory"
#define ONCHIP_MEMORY_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY_SIZE_VALUE 184320
#define ONCHIP_MEMORY_SPAN 184320
#define ONCHIP_MEMORY_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY_WRITABLE 1


/*
 * power_led configuration
 *
 */

#define ALT_MODULE_CLASS_power_led altera_avalon_pio
#define POWER_LED_BASE 0x82160
#define POWER_LED_BIT_CLEARING_EDGE_REGISTER 0
#define POWER_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define POWER_LED_CAPTURE 0
#define POWER_LED_DATA_WIDTH 1
#define POWER_LED_DO_TEST_BENCH_WIRING 0
#define POWER_LED_DRIVEN_SIM_VALUE 0
#define POWER_LED_EDGE_TYPE "NONE"
#define POWER_LED_FREQ 100000000
#define POWER_LED_HAS_IN 0
#define POWER_LED_HAS_OUT 1
#define POWER_LED_HAS_TRI 0
#define POWER_LED_IRQ -1
#define POWER_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define POWER_LED_IRQ_TYPE "NONE"
#define POWER_LED_NAME "/dev/power_led"
#define POWER_LED_RESET_VALUE 0
#define POWER_LED_SPAN 16
#define POWER_LED_TYPE "altera_avalon_pio"


/*
 * protocol_fifo_in configuration
 *
 */

#define ALT_MODULE_CLASS_protocol_fifo_in altera_avalon_fifo
#define PROTOCOL_FIFO_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define PROTOCOL_FIFO_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define PROTOCOL_FIFO_IN_BASE 0x821e8
#define PROTOCOL_FIFO_IN_BITS_PER_SYMBOL 16
#define PROTOCOL_FIFO_IN_CHANNEL_WIDTH 0
#define PROTOCOL_FIFO_IN_ERROR_WIDTH 0
#define PROTOCOL_FIFO_IN_FIFO_DEPTH 1024
#define PROTOCOL_FIFO_IN_IRQ -1
#define PROTOCOL_FIFO_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PROTOCOL_FIFO_IN_NAME "/dev/protocol_fifo_in"
#define PROTOCOL_FIFO_IN_SINGLE_CLOCK_MODE 1
#define PROTOCOL_FIFO_IN_SPAN 8
#define PROTOCOL_FIFO_IN_SYMBOLS_PER_BEAT 2
#define PROTOCOL_FIFO_IN_TYPE "altera_avalon_fifo"
#define PROTOCOL_FIFO_IN_USE_AVALONMM_READ_SLAVE 0
#define PROTOCOL_FIFO_IN_USE_AVALONMM_WRITE_SLAVE 1
#define PROTOCOL_FIFO_IN_USE_AVALONST_SINK 0
#define PROTOCOL_FIFO_IN_USE_AVALONST_SOURCE 1
#define PROTOCOL_FIFO_IN_USE_BACKPRESSURE 1
#define PROTOCOL_FIFO_IN_USE_IRQ 0
#define PROTOCOL_FIFO_IN_USE_PACKET 0
#define PROTOCOL_FIFO_IN_USE_READ_CONTROL 0
#define PROTOCOL_FIFO_IN_USE_REGISTER 0
#define PROTOCOL_FIFO_IN_USE_WRITE_CONTROL 1


/*
 * protocol_fifo_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_protocol_fifo_in_csr altera_avalon_fifo
#define PROTOCOL_FIFO_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define PROTOCOL_FIFO_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define PROTOCOL_FIFO_IN_CSR_BASE 0x82100
#define PROTOCOL_FIFO_IN_CSR_BITS_PER_SYMBOL 16
#define PROTOCOL_FIFO_IN_CSR_CHANNEL_WIDTH 0
#define PROTOCOL_FIFO_IN_CSR_ERROR_WIDTH 0
#define PROTOCOL_FIFO_IN_CSR_FIFO_DEPTH 1024
#define PROTOCOL_FIFO_IN_CSR_IRQ -1
#define PROTOCOL_FIFO_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define PROTOCOL_FIFO_IN_CSR_NAME "/dev/protocol_fifo_in_csr"
#define PROTOCOL_FIFO_IN_CSR_SINGLE_CLOCK_MODE 1
#define PROTOCOL_FIFO_IN_CSR_SPAN 32
#define PROTOCOL_FIFO_IN_CSR_SYMBOLS_PER_BEAT 2
#define PROTOCOL_FIFO_IN_CSR_TYPE "altera_avalon_fifo"
#define PROTOCOL_FIFO_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define PROTOCOL_FIFO_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define PROTOCOL_FIFO_IN_CSR_USE_AVALONST_SINK 0
#define PROTOCOL_FIFO_IN_CSR_USE_AVALONST_SOURCE 1
#define PROTOCOL_FIFO_IN_CSR_USE_BACKPRESSURE 1
#define PROTOCOL_FIFO_IN_CSR_USE_IRQ 0
#define PROTOCOL_FIFO_IN_CSR_USE_PACKET 0
#define PROTOCOL_FIFO_IN_CSR_USE_READ_CONTROL 0
#define PROTOCOL_FIFO_IN_CSR_USE_REGISTER 0
#define PROTOCOL_FIFO_IN_CSR_USE_WRITE_CONTROL 1


/*
 * spird_fifo_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_spird_fifo_in_csr altera_avalon_fifo
#define SPIRD_FIFO_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define SPIRD_FIFO_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define SPIRD_FIFO_IN_CSR_BASE 0x820c0
#define SPIRD_FIFO_IN_CSR_BITS_PER_SYMBOL 16
#define SPIRD_FIFO_IN_CSR_CHANNEL_WIDTH 0
#define SPIRD_FIFO_IN_CSR_ERROR_WIDTH 0
#define SPIRD_FIFO_IN_CSR_FIFO_DEPTH 2048
#define SPIRD_FIFO_IN_CSR_IRQ -1
#define SPIRD_FIFO_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPIRD_FIFO_IN_CSR_NAME "/dev/spird_fifo_in_csr"
#define SPIRD_FIFO_IN_CSR_SINGLE_CLOCK_MODE 1
#define SPIRD_FIFO_IN_CSR_SPAN 32
#define SPIRD_FIFO_IN_CSR_SYMBOLS_PER_BEAT 2
#define SPIRD_FIFO_IN_CSR_TYPE "altera_avalon_fifo"
#define SPIRD_FIFO_IN_CSR_USE_AVALONMM_READ_SLAVE 1
#define SPIRD_FIFO_IN_CSR_USE_AVALONMM_WRITE_SLAVE 0
#define SPIRD_FIFO_IN_CSR_USE_AVALONST_SINK 1
#define SPIRD_FIFO_IN_CSR_USE_AVALONST_SOURCE 0
#define SPIRD_FIFO_IN_CSR_USE_BACKPRESSURE 1
#define SPIRD_FIFO_IN_CSR_USE_IRQ 0
#define SPIRD_FIFO_IN_CSR_USE_PACKET 0
#define SPIRD_FIFO_IN_CSR_USE_READ_CONTROL 0
#define SPIRD_FIFO_IN_CSR_USE_REGISTER 0
#define SPIRD_FIFO_IN_CSR_USE_WRITE_CONTROL 1


/*
 * spird_fifo_out configuration
 *
 */

#define ALT_MODULE_CLASS_spird_fifo_out altera_avalon_fifo
#define SPIRD_FIFO_OUT_AVALONMM_AVALONMM_DATA_WIDTH 32
#define SPIRD_FIFO_OUT_AVALONMM_AVALONST_DATA_WIDTH 32
#define SPIRD_FIFO_OUT_BASE 0x821d8
#define SPIRD_FIFO_OUT_BITS_PER_SYMBOL 16
#define SPIRD_FIFO_OUT_CHANNEL_WIDTH 0
#define SPIRD_FIFO_OUT_ERROR_WIDTH 0
#define SPIRD_FIFO_OUT_FIFO_DEPTH 2048
#define SPIRD_FIFO_OUT_IRQ -1
#define SPIRD_FIFO_OUT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPIRD_FIFO_OUT_NAME "/dev/spird_fifo_out"
#define SPIRD_FIFO_OUT_SINGLE_CLOCK_MODE 1
#define SPIRD_FIFO_OUT_SPAN 8
#define SPIRD_FIFO_OUT_SYMBOLS_PER_BEAT 2
#define SPIRD_FIFO_OUT_TYPE "altera_avalon_fifo"
#define SPIRD_FIFO_OUT_USE_AVALONMM_READ_SLAVE 1
#define SPIRD_FIFO_OUT_USE_AVALONMM_WRITE_SLAVE 0
#define SPIRD_FIFO_OUT_USE_AVALONST_SINK 1
#define SPIRD_FIFO_OUT_USE_AVALONST_SOURCE 0
#define SPIRD_FIFO_OUT_USE_BACKPRESSURE 1
#define SPIRD_FIFO_OUT_USE_IRQ 0
#define SPIRD_FIFO_OUT_USE_PACKET 0
#define SPIRD_FIFO_OUT_USE_READ_CONTROL 0
#define SPIRD_FIFO_OUT_USE_REGISTER 0
#define SPIRD_FIFO_OUT_USE_WRITE_CONTROL 1


/*
 * spiwr_fifo_in configuration
 *
 */

#define ALT_MODULE_CLASS_spiwr_fifo_in altera_avalon_fifo
#define SPIWR_FIFO_IN_AVALONMM_AVALONMM_DATA_WIDTH 32
#define SPIWR_FIFO_IN_AVALONMM_AVALONST_DATA_WIDTH 32
#define SPIWR_FIFO_IN_BASE 0x821e0
#define SPIWR_FIFO_IN_BITS_PER_SYMBOL 16
#define SPIWR_FIFO_IN_CHANNEL_WIDTH 0
#define SPIWR_FIFO_IN_ERROR_WIDTH 0
#define SPIWR_FIFO_IN_FIFO_DEPTH 16
#define SPIWR_FIFO_IN_IRQ -1
#define SPIWR_FIFO_IN_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPIWR_FIFO_IN_NAME "/dev/spiwr_fifo_in"
#define SPIWR_FIFO_IN_SINGLE_CLOCK_MODE 1
#define SPIWR_FIFO_IN_SPAN 8
#define SPIWR_FIFO_IN_SYMBOLS_PER_BEAT 2
#define SPIWR_FIFO_IN_TYPE "altera_avalon_fifo"
#define SPIWR_FIFO_IN_USE_AVALONMM_READ_SLAVE 0
#define SPIWR_FIFO_IN_USE_AVALONMM_WRITE_SLAVE 1
#define SPIWR_FIFO_IN_USE_AVALONST_SINK 0
#define SPIWR_FIFO_IN_USE_AVALONST_SOURCE 1
#define SPIWR_FIFO_IN_USE_BACKPRESSURE 1
#define SPIWR_FIFO_IN_USE_IRQ 0
#define SPIWR_FIFO_IN_USE_PACKET 0
#define SPIWR_FIFO_IN_USE_READ_CONTROL 0
#define SPIWR_FIFO_IN_USE_REGISTER 0
#define SPIWR_FIFO_IN_USE_WRITE_CONTROL 1


/*
 * spiwr_fifo_in_csr configuration
 *
 */

#define ALT_MODULE_CLASS_spiwr_fifo_in_csr altera_avalon_fifo
#define SPIWR_FIFO_IN_CSR_AVALONMM_AVALONMM_DATA_WIDTH 32
#define SPIWR_FIFO_IN_CSR_AVALONMM_AVALONST_DATA_WIDTH 32
#define SPIWR_FIFO_IN_CSR_BASE 0x820e0
#define SPIWR_FIFO_IN_CSR_BITS_PER_SYMBOL 16
#define SPIWR_FIFO_IN_CSR_CHANNEL_WIDTH 0
#define SPIWR_FIFO_IN_CSR_ERROR_WIDTH 0
#define SPIWR_FIFO_IN_CSR_FIFO_DEPTH 16
#define SPIWR_FIFO_IN_CSR_IRQ -1
#define SPIWR_FIFO_IN_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SPIWR_FIFO_IN_CSR_NAME "/dev/spiwr_fifo_in_csr"
#define SPIWR_FIFO_IN_CSR_SINGLE_CLOCK_MODE 1
#define SPIWR_FIFO_IN_CSR_SPAN 32
#define SPIWR_FIFO_IN_CSR_SYMBOLS_PER_BEAT 2
#define SPIWR_FIFO_IN_CSR_TYPE "altera_avalon_fifo"
#define SPIWR_FIFO_IN_CSR_USE_AVALONMM_READ_SLAVE 0
#define SPIWR_FIFO_IN_CSR_USE_AVALONMM_WRITE_SLAVE 1
#define SPIWR_FIFO_IN_CSR_USE_AVALONST_SINK 0
#define SPIWR_FIFO_IN_CSR_USE_AVALONST_SOURCE 1
#define SPIWR_FIFO_IN_CSR_USE_BACKPRESSURE 1
#define SPIWR_FIFO_IN_CSR_USE_IRQ 0
#define SPIWR_FIFO_IN_CSR_USE_PACKET 0
#define SPIWR_FIFO_IN_CSR_USE_READ_CONTROL 0
#define SPIWR_FIFO_IN_CSR_USE_REGISTER 0
#define SPIWR_FIFO_IN_CSR_USE_WRITE_CONTROL 1


/*
 * status_led configuration
 *
 */

#define ALT_MODULE_CLASS_status_led altera_avalon_pio
#define STATUS_LED_BASE 0x82150
#define STATUS_LED_BIT_CLEARING_EDGE_REGISTER 0
#define STATUS_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STATUS_LED_CAPTURE 0
#define STATUS_LED_DATA_WIDTH 1
#define STATUS_LED_DO_TEST_BENCH_WIRING 0
#define STATUS_LED_DRIVEN_SIM_VALUE 0
#define STATUS_LED_EDGE_TYPE "NONE"
#define STATUS_LED_FREQ 100000000
#define STATUS_LED_HAS_IN 0
#define STATUS_LED_HAS_OUT 1
#define STATUS_LED_HAS_TRI 0
#define STATUS_LED_IRQ -1
#define STATUS_LED_IRQ_INTERRUPT_CONTROLLER_ID -1
#define STATUS_LED_IRQ_TYPE "NONE"
#define STATUS_LED_NAME "/dev/status_led"
#define STATUS_LED_RESET_VALUE 0
#define STATUS_LED_SPAN 16
#define STATUS_LED_TYPE "altera_avalon_pio"


/*
 * sysid configuration
 *
 */

#define ALT_MODULE_CLASS_sysid altera_avalon_sysid_qsys
#define SYSID_BASE 0x821f0
#define SYSID_ID 74565
#define SYSID_IRQ -1
#define SYSID_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_NAME "/dev/sysid"
#define SYSID_SPAN 8
#define SYSID_TIMESTAMP 1577438561
#define SYSID_TYPE "altera_avalon_sysid_qsys"


/*
 * w5500_cs configuration
 *
 */

#define ALT_MODULE_CLASS_w5500_cs altera_avalon_pio
#define W5500_CS_BASE 0x82190
#define W5500_CS_BIT_CLEARING_EDGE_REGISTER 0
#define W5500_CS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define W5500_CS_CAPTURE 0
#define W5500_CS_DATA_WIDTH 1
#define W5500_CS_DO_TEST_BENCH_WIRING 0
#define W5500_CS_DRIVEN_SIM_VALUE 0
#define W5500_CS_EDGE_TYPE "NONE"
#define W5500_CS_FREQ 100000000
#define W5500_CS_HAS_IN 0
#define W5500_CS_HAS_OUT 1
#define W5500_CS_HAS_TRI 0
#define W5500_CS_IRQ -1
#define W5500_CS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define W5500_CS_IRQ_TYPE "NONE"
#define W5500_CS_NAME "/dev/w5500_cs"
#define W5500_CS_RESET_VALUE 0
#define W5500_CS_SPAN 16
#define W5500_CS_TYPE "altera_avalon_pio"


/*
 * w5500_int configuration
 *
 */

#define ALT_MODULE_CLASS_w5500_int altera_avalon_pio
#define W5500_INT_BASE 0x821a0
#define W5500_INT_BIT_CLEARING_EDGE_REGISTER 0
#define W5500_INT_BIT_MODIFYING_OUTPUT_REGISTER 0
#define W5500_INT_CAPTURE 0
#define W5500_INT_DATA_WIDTH 1
#define W5500_INT_DO_TEST_BENCH_WIRING 0
#define W5500_INT_DRIVEN_SIM_VALUE 0
#define W5500_INT_EDGE_TYPE "NONE"
#define W5500_INT_FREQ 100000000
#define W5500_INT_HAS_IN 1
#define W5500_INT_HAS_OUT 1
#define W5500_INT_HAS_TRI 0
#define W5500_INT_IRQ -1
#define W5500_INT_IRQ_INTERRUPT_CONTROLLER_ID -1
#define W5500_INT_IRQ_TYPE "NONE"
#define W5500_INT_NAME "/dev/w5500_int"
#define W5500_INT_RESET_VALUE 0
#define W5500_INT_SPAN 16
#define W5500_INT_TYPE "altera_avalon_pio"


/*
 * w5500_rst configuration
 *
 */

#define ALT_MODULE_CLASS_w5500_rst altera_avalon_pio
#define W5500_RST_BASE 0x821b0
#define W5500_RST_BIT_CLEARING_EDGE_REGISTER 0
#define W5500_RST_BIT_MODIFYING_OUTPUT_REGISTER 0
#define W5500_RST_CAPTURE 0
#define W5500_RST_DATA_WIDTH 1
#define W5500_RST_DO_TEST_BENCH_WIRING 0
#define W5500_RST_DRIVEN_SIM_VALUE 0
#define W5500_RST_EDGE_TYPE "NONE"
#define W5500_RST_FREQ 100000000
#define W5500_RST_HAS_IN 0
#define W5500_RST_HAS_OUT 1
#define W5500_RST_HAS_TRI 0
#define W5500_RST_IRQ -1
#define W5500_RST_IRQ_INTERRUPT_CONTROLLER_ID -1
#define W5500_RST_IRQ_TYPE "NONE"
#define W5500_RST_NAME "/dev/w5500_rst"
#define W5500_RST_RESET_VALUE 0
#define W5500_RST_SPAN 16
#define W5500_RST_TYPE "altera_avalon_pio"


/*
 * watchdog configuration
 *
 */

#define ALT_MODULE_CLASS_watchdog altera_avalon_timer
#define WATCHDOG_ALWAYS_RUN 1
#define WATCHDOG_BASE 0x82080
#define WATCHDOG_COUNTER_SIZE 32
#define WATCHDOG_FIXED_PERIOD 1
#define WATCHDOG_FREQ 100000000
#define WATCHDOG_IRQ 4
#define WATCHDOG_IRQ_INTERRUPT_CONTROLLER_ID 0
#define WATCHDOG_LOAD_VALUE 499999999
#define WATCHDOG_MULT 1.0
#define WATCHDOG_NAME "/dev/watchdog"
#define WATCHDOG_PERIOD 5
#define WATCHDOG_PERIOD_UNITS "s"
#define WATCHDOG_RESET_OUTPUT 1
#define WATCHDOG_SNAPSHOT 0
#define WATCHDOG_SPAN 32
#define WATCHDOG_TICKS_PER_SEC 0
#define WATCHDOG_TIMEOUT_PULSE_OUTPUT 0
#define WATCHDOG_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
